"""initial migration

Revision ID: 019805fc0f4a
Revises: 
Create Date: 2017-01-06 16:16:55.112761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019805fc0f4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager')
    # ### end Alembic commands ###
